# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vc709.xdc

# IP: ip/ten_gig_eth_pcs_pma_0/ten_gig_eth_pcs_pma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_0 || ORIG_REF_NAME==ten_gig_eth_pcs_pma_0} -quiet] -quiet
