# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Kumar Lab/Desktop/Jasper/xilinx_rx/xilinx_rx.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xci
# IP: The module: 'gtwizard_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Kumar Lab/Desktop/Jasper/xilinx_rx/xilinx_rx.gen/sources_1/ip/gtwizard_0/gtwizard_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Kumar Lab/Desktop/Jasper/xilinx_rx/xilinx_rx.gen/sources_1/ip/gtwizard_0/gtwizard_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Kumar Lab/Desktop/Jasper/xilinx_rx/xilinx_rx.srcs/sources_1/ip/gtwizard_0/gtwizard_0.xci
# IP: The module: 'gtwizard_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Kumar Lab/Desktop/Jasper/xilinx_rx/xilinx_rx.gen/sources_1/ip/gtwizard_0/gtwizard_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Kumar Lab/Desktop/Jasper/xilinx_rx/xilinx_rx.gen/sources_1/ip/gtwizard_0/gtwizard_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
