set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]

set_property PACKAGE_PIN H19 [get_ports sysclk_p]
set_property PACKAGE_PIN G18 [get_ports sysclk_n]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {sysclk_p sysclk_n}]
create_clock -period 5.000 -name sysclk_200 [get_ports sysclk_p]

set_property PACKAGE_PIN AK34 [get_ports user_clock_p]
set_property PACKAGE_PIN AL34 [get_ports user_clock_n]
set_property IOSTANDARD LVDS [get_ports {user_clock_p user_clock_n}]
create_clock -period 6.400 -name si570_156m25 [get_ports user_clock_p]
set_property PACKAGE_PIN AJ32 [get_ports ref_clk_sma_p]
set_property PACKAGE_PIN AK32 [get_ports ref_clk_sma_n]
set_property IOSTANDARD LVDS [get_ports {ref_clk_sma_p ref_clk_sma_n}]

set_property PACKAGE_PIN AK8 [get_ports gt_refclk_p]
set_property PACKAGE_PIN AK7 [get_ports gt_refclk_n]
create_clock -period 6.400 -name gt_refclk_156m25 [get_ports gt_refclk_p]

set_property PACKAGE_PIN AV40 [get_ports cpu_reset_n]
set_property IOSTANDARD LVCMOS18 [get_ports cpu_reset_n]

set_property PACKAGE_PIN AM39 [get_ports {gpio_led[0]}]
set_property PACKAGE_PIN AN39 [get_ports {gpio_led[1]}]
set_property PACKAGE_PIN AR37 [get_ports {gpio_led[2]}]
set_property PACKAGE_PIN AT37 [get_ports {gpio_led[3]}]
set_property PACKAGE_PIN AR35 [get_ports {gpio_led[4]}]
set_property PACKAGE_PIN AP41 [get_ports {gpio_led[5]}]
set_property PACKAGE_PIN AP42 [get_ports {gpio_led[6]}]
set_property PACKAGE_PIN AU39 [get_ports {gpio_led[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_led[*]}]

set_property PACKAGE_PIN AN6 [get_ports sfp_rx_p]
set_property PACKAGE_PIN AN5 [get_ports sfp_rx_n]
set_property PACKAGE_PIN AB41 [get_ports sfp1_tx_disable]
set_property PACKAGE_PIN Y38  [get_ports sfp1_tx_fault]
set_property PACKAGE_PIN AB42 [get_ports sfp1_mod_abs]
set_property PACKAGE_PIN Y39  [get_ports sfp1_los]
set_property PACKAGE_PIN W40  [get_ports sfp1_rs0]
set_property PACKAGE_PIN Y40  [get_ports sfp1_rs1]
set_property IOSTANDARD LVCMOS18 [get_ports {sfp1_tx_disable sfp1_tx_fault sfp1_mod_abs sfp1_los sfp1_rs0 sfp1_rs1}]

set_property LOC GTHE2_CHANNEL_X1Y12 [get_cells -hierarchical -filter {REF_NAME == GTHE2_CHANNEL}]
set_clock_groups -asynchronous \
    -group [get_clocks -include_generated_clocks sysclk_200] \
    -group [get_clocks -include_generated_clocks si570_156m25] \
    -group [get_clocks -include_generated_clocks gt_refclk_156m25]

# rx_fsm_done is generated by the GT startup FSM on the stable 100-MHz
# clock and is intentionally captured by the two-stage ASYNC_REG synchronizer
# in the recovered RXUSRCLK2 domain.  There is no phase relationship to time.
set_clock_groups -asynchronous \
    -group [get_clocks clk_100_unbuffered] \
    -group [get_clocks rxusrclk2_unbuffered]
