# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Kumar Lab/Desktop/Jasper/xilinx_rx/xilinx_rx.srcs/constrs_1/new/vc709.xdc

# IP: C:/Users/Kumar Lab/Desktop/Jasper/xilinx_rx/xilinx_rx.srcs/sources_1/ip/ten_gig_eth_pcs_pma_0/ten_gig_eth_pcs_pma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ten_gig_eth_pcs_pma_0 || ORIG_REF_NAME==ten_gig_eth_pcs_pma_0} -quiet] -quiet
